### ISSUE TITLE
Build instructions and dependencies

### ISSUE THREAD

**Issue by carlosedp** [j-marjanovic/jtag-quartus-ft232h#1]
I've checked-out the project and also the openocd repository in version v0.11.0.

After running `copy_openocd_files.sh` and `cmake .`, the build complains about missing files (some were found on openocd repo under `src/helper` but some were not found.

It complains about missing `jim.h` also.

Any pointers to which openocd this driver should be compiled against?

**Comment by j-marjanovic** [comment]
`copy_openocd_files.sh` is just a convenience script for developers. This is maybe different to other projects where such script are provided because of the licensing reasons - this is not the case here.

The files from OpenOCD were modified for standalone use in commit 94ac3b0

To build the library the following commands should suffice (tested on Ubuntu 20.10): `mkdir build && cd build && cmake .. && make`

**Comment by j-marjanovic** [comment]
`libjim-dev` also needs to be installed

**Comment by j-marjanovic** [comment]
@carlosedp could you please confirm that using the above instructions you are able to compile the library?

**Comment by carlosedp** [comment]
Ah yes, it worked perfectly!
I'll submit a PR to the Readme adding the instructions and dependencies.

**Comment by j-marjanovic** [comment]
ok, perfect, thanks!
